resolver: lts-5.12

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- SHA2-0.2.5
- ed25519-donna-0.1.1
- unagi-chan-0.4.0.0
- ed25519-donna-0.1.1
- AES-0.2.9
- megaparsec-4.2.0
# Are these required because a dependency of this project is using data-dword, or because masala is using data-dword and extra-deps aren't propagated?
- data-dword-0.3
- data-bword-0.1 # for data-dword
- vector-0.11.0.0
- ekg-0.4.0.9
- ekg-json-0.1.0.1
- lens-4.13.2.1
- kan-extensions-5.0.1
- lz4-0.2.3.1

# Override default flag values for local packages and extra-deps
# flags: []

# Extra package databases containing global packages
extra-package-dbs: []

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
